language: node_js
node_js:
- node
services: postgres
script:
  - npm test -- --coverage
env:
  global:
    - FILE="__test__/postgres.mock.sql"
    - TEST_DB_FILE="`pwd`/$FILE"
before_script:
  - echo $TEST_DB_FILE
  - echo "$TEST_DB_FILE"
  - psql -f "$TEST_DB_FILE"
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls